name: test_cicd

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  install_and_run_rspec:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependence
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
        
      - name: Install gems
        run: |
          bundle install
      
      - name: Add TailwindCSS
        run: |
          bundle exec rails tailwindcss:install
          bundle exec rails assets:precompile

      - name: Prepare database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: password
          RAILS_ENV: test
        run: |
          bundle exec rails db:prepare

      - name: Run Rspec test
        run: |
          bundle exec rspec